server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/lab
    username: postgres
    password: 123456

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true

  data:
    jdbc:
      dialect: postgresql

  sql:
    init:
#      data-locations: classpath:sql/presentation/create_test_data.sql
      mode: always


