server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/lab
    username: postgres
    password: 123456

  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
      init-presentation-data: true
#      ddl-auto: none
#      init-presentation-data: false


  data:
    jdbc:
      dialect: postgresql

  freemarker:
    templateLoaderPath: classpath:/templates/
    suffix: .ftl
    charset: UTF-8
    content-type: text/html

experiment:
  defaults:
    unknown: "---unknown---"
