<!DOCTYPE html>
<html lang="ru">
<head>
    <title>Эксперимент ${experiment.id}</title>
    <link rel="stylesheet" type="text/css" href="/css/styles.css">
</head>
<body>
<#include "common/header.ftl">
<main>
    <table>
        <tr>
            <th>Field</th><th>Value</th>
        </tr>
        <tr>
            <td>id</td><td>${experiment.id}</td>
        </tr>
        <tr>
            <td>createdAt</td><td>${experiment.createdAt}</td>
        </tr>
        <tr>
            <td>createdBy</td><td>${experiment.createdBy}</td>
        </tr>
        <tr>
            <td>lastUpdatedAt</td><td>${experiment.lastUpdatedAt}</td>
        </tr>
        <tr>
            <td>statusDescription</td><td>${experiment.statusDescription}</td>
        </tr>
        <tr>
            <td>statusName</td><td>${experiment.statusName}</td>
        </tr>
        <tr>
            <td>equipmentName</td><td>${experiment.equipmentName}</td>
        </tr>
        <tr>
            <td>equipmentType</td><td>${experiment.equipmentType}</td>
        </tr>
        <tr>
            <td>materials</td>
            <td>
                <table>
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>Type</th>
                    </tr>
                    </thead>
                    <tbody>
                    <#list experiment.materials as material>
                        <tr>
                            <td>${material.name}</td>
                            <td>${material.type}</td>
                        </tr>
                    </#list>
                    </tbody>
                </table>
            </td>
        </tr>
        <tr>
            <td>actionName</td><td>${experiment.actionName}</td>
        </tr>
        <tr>
            <td>reportText</td><td>${experiment.reportText}</td>
        </tr>
        <tr>
            <td>reportResult</td><td>${experiment.reportResult}</td>
        </tr>
    </table>
    </main>
</body>
</html>